dimensions:
  num_agents: 10
  num_items: 10
  num_features: 5
  num_simuls: 1
sigma: 1.0
modular_agent_features: 3
modular_item_features: 2
num_replications: 2
base_seed: 12345
results_csv: debug_results.csv
subproblem:
  name: LinearKnapsack
  settings:
    TimeLimit: 60
    MIPGap_tol: 0.01
row_generation:
  max_iters: 100
  min_iters: 1
  tolerance_optimality: 0.001
  gurobi_settings:
    OutputFlag: 0
  theta_ubs: 100
ellipsoid:
  solver_precision: 1.0e-06
  tolerance: 1.0e-06
  initial_radius: 2.0
  decay_factor: 0.95
  min_volume: 1.0e-12
  verbose: false
