dimensions:
  num_agents: 100
  num_items: 100
  num_features: 6
  num_simuls: 1
sigma: 5.0
modular_agent_features: 5
quadratic_item_features: 1
num_replications: 2
base_seed: 12345
results_csv: debug_results.csv
subproblem:
  name: QuadSupermodularNetwork
row_generation:
  max_iters: 100
  min_iters: 1
  tolerance_optimality: 0.001
  gurobi_settings:
    OutputFlag: 0
  theta_ubs: 100
ellipsoid:
  solver_precision: 1.0e-06
  tolerance: 1.0e-06
  initial_radius: 1.0
  decay_factor: 0.95
  min_volume: 1.0e-12
  verbose: false
