# Sandwich SE Configuration (Cluster)
# ====================================

# Application parameters
application:
    delta: 4
    winners_only: false
    hq_distance: false

# Sandwich SE settings
sandwich:
    num_simulations: 200
    step_size: 1e-4
    seed: 1995

# BundleChoice settings
dimensions:
    num_obs: 255
    num_items: 493
    num_features: 497
    num_simulations: 1

subproblem: 
    name: QuadKnapsack
    settings:
        TimeLimit: 30
        MIPGap_tol: 1e-2
