dimensions:
    num_agents: 255
    num_items: 493
    num_features: 497  # Will be updated from theta_true
    num_simuls: 100

subproblem: 
    name: QuadKnapsack
    settings:
        TimeLimit: 3
        MIPGap_tol: 1e-2
row_generation:
    max_iters: 300
    theta_ubs: 1000
    parameters_to_log: [0, -3,-2,-1]
    max_slack_counter: 8
    tolerance_optimality: 1e-4
    gurobi_settings:
        OutputFlag: 0

